### ISSUE TITLE
salt2 v1.0 broken

### ISSUE THREAD

**Issue by AlexGKim** [sncosmo/sncosmo#91] opened 2015-04-17 20:30 UTC
## In [102]: sncosmo.registry.retrieve(sncosmo.Source,'salt2', version='1.0')

ValueError                                Traceback (most recent call last)
<ipython-input-102-e87d91b1514b> in <module>()
----> 1 sncosmo.registry.retrieve(sncosmo.Source,'salt2', version='1.0')

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sncosmo-1.1.dev516-py2.7-macosx-10.6-x86_64.egg/sncosmo/registry.pyc in retrieve(data_class, name, version)
    181             _instances[key] = func(_args, name=name)
    182         else:
--> 183             _instances[key] = func(_args, name=name, version=version)
    184         return _instances[key]
    185 

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sncosmo-1.1.dev516-py2.7-macosx-10.6-x86_64.egg/sncosmo/builtins.pyc in load_salt2model(relpath, name, version)
    161 def load_salt2model(relpath, name=None, version=None):
    162     abspath = get_abspath(relpath, name, version=version)
--> 163     return SALT2Source(modeldir=abspath, name=name, version=version)
    164 
    165 

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sncosmo-1.1.dev516-py2.7-macosx-10.6-x86_64.egg/sncosmo/models.pyc in **init**(self, modeldir, m0file, m1file, clfile, cdfile, errscalefile, lcrv00file, lcrv11file, lcrv01file, name, version)
    685 
    686         # Set the color dispersion from "color_dispersion" file
--> 687         w, val = np.loadtxt(names_or_objs['cdfile'], unpack=True)
    688         self._colordisp = Spline1d(w, val,  k=1)  # linear interp.
    689 

/Users/akim/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/lib/npyio.pyc in loadtxt(fname, dtype, comments, delimiter, converters, skiprows, usecols, unpack, ndmin)
    858 
    859             # Convert each value according to its column and store
--> 860             items = [conv(val) for (conv, val) in zip(converters, vals)]
    861             # Then pack it according to the dtype's nesting
    862             items = pack_items(items, packing)

ValueError: could not convert string to float: @kU

**Comment by kbarbary** [comment] 2015-04-18 05:58
I can confirm this bug. Looks like a problem in parsing the "color dispersion" file; It's completely different in SALT2 1.0 vs SALT2 2.0+, and I think the file parser was written with v2.0+ format in mind.

In the meantime, version 2.0+ should work.

Also, be aware that writing `@kU` in github issues notifies the github user with the username `ku`. This wasn't your fault - just unlucky that the SALT2 file happened to have the string `@kU` in it, and that was reported in the error. You can avoid this sort of thing by putting quoted code or error messages in single backticks within a paragraph, or using triple backticks for multi-line blocks. It also makes it easier to read. See the github markdown  help (the "markdown supported" button on the text entry box).

**Comment by kbarbary** [comment] 2015-04-18 06:13
I think this bug was introduced when @rbiswas4 and I added color dispersion support to the SALT2 model... we most likely never tried to use it with SALT2 v1.0.

I'm not even sure how to interpret this file. The entire file is just
```
@kU 0.0218
@kR 0.0179
```

whereas SALT2 v2.0+ looks like
```
# l : wavelength
# s : sigma
#end
2500 0.589197
2510 0.5736
2520 0.558487
2530 0.543842
2540 0.529649
2550 0.515892
2560 0.502556
2570 0.489627
2580 0.47709
2590 0.464934
2600 0.453144
```
Color dispersion should be a scalar function of wavelength. How do we translate the file with two numbers into such a function? Perhaps @rbiswas4 knows?

**Comment by rbiswas4** [comment] 2015-04-18 06:21
Sorry, but I am confused.  What do these version names stand for? There is SALT2 Guy 2007, SALT2 Guy 2010, and then a SALT2 model released as part of Betoule 2014. Is SALT2 v1.0 Guy2007? And what/where are the files that correspond to color dispersion?

**Comment by kbarbary** [comment] 2015-04-18 06:30
The version names correspond to the versions given on SALT2 homepage: http://supernovae.in2p3.fr/salt/doku.php?id=salt_templates. Guy 2007 corresponds to v1.0.

The color dispersion file is `salt2_color_dispersion.dat` in the unpacked tar directory of the distributed data. Using sncosmo, it will be at `[data dir]/models/salt2/salt2/salt2_color_dispersion.dat` after you try to do `sncosmo.get_source('salt2', version='v1.0')` (where `[data dir]` is the cache directory or wherever you've configured the data directory to be).

I guess we'll have to look at the snfit source code to figure out how to interpret the v1.0 file format.

**Comment by dannygoldstein** [comment] 2015-11-06 05:32
``` python
In [1]: import sncosmo as sn

In [2]: sn.Model(source='salt2')
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-575512c26b62> in <module>()
----> 1 sn.Model(source='salt2')

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/models.pyc in __init__(self, source, effects, effect_names, effect_frames)
   1006         self.param_names_latex = ['z', 't_0']
   1007         self._parameters = np.array([0., 0.])
-> 1008         self._source = get_source(source, copy=True)
   1009         self.description = None
   1010         self._effects = []

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/models.pyc in get_source(name, version, copy)
     86             return name
     87     else:
---> 88         return cp(registry.retrieve(Source, name, version=version))
     89
     90

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/registry.pyc in retrieve(data_class, name, version)
    194             regkey = (key[0], key[1], latest_version)
    195             func, args, meta = _loaders[regkey]
--> 196             _instances[regkey] = func(*args, name=name, version=latest_version)
    197             _instances[key] = _instances[regkey]
    198             return _instances[key]

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/builtins.pyc in load_salt2model(relpath, name, version)
    158
    159 def load_salt2model(relpath, name=None, version=None):
--> 160     abspath = get_abspath(relpath, name, version=version)
    161     return SALT2Source(modeldir=abspath)
    162

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/builtins.pyc in get_abspath(relpath, name, version)
    100         if url.endswith(".tar.gz") or url.endswith(".tar"):
    101             dirname = os.path.dirname(abspath)
--> 102             download_dir(url, dirname)
    103
    104             # ensure that tarfile unpacked into the expected directory

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/utils.pyc in download_dir(remote_url, dirname)
    350     # download file to buffer
    351     buf = io.BytesIO()
--> 352     _download_file(remote_url, buf)
    353     buf.seek(0)
    354

/Users/dgold/miniconda/lib/python2.7/site-packages/sncosmo/utils.pyc in _download_file(remote_url, target)
    276     # way, but for some reason in mysterious circumstances it doesn't. So
    277     # we'll just re-raise it here instead.
--> 278     except socket.timeout as e:
    279         raise URLError(e)
    280

NameError: global name 'socket' is not defined
```

**Comment by rbiswas4** [comment] 2015-11-06 05:55
Last week, Pierre-Francois Leget found this too and was going to submit an issue/email Kyle. I believe he figured out that he could correct the issue by adding `import socket` to utils.py .... don't have his github id, but will remind him on email.

**Comment by dannygoldstein** [comment] 2015-11-06 06:12
Looks like this is fixed in 1.1. I was running with 1.0.

On Fri, Nov 6, 2015 at 2:55 AM, rbiswas4 <notifications@github.com> wrote:

> Last week, Pierre-Francois Leget found this too and was going to submit an
> issue/email Kyle. I believe he figured out that he could correct the issue
> by adding import socket to utils.py .... don't have his github id, but
> will remind him on email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sncosmo/sncosmo/issues/91#issuecomment-154308246>.
>



-- 
Danny Goldstein
Computational Cosmology Center
Lawrence Berkeley National Lab
1 Cyclotron Road Mail Stop 50B4206
Berkeley, California 94720-8151
http://astro.berkeley.edu/~dgold/

**Comment by kbarbary** [comment] 2015-11-06 10:58
Just fixed on master. See sncosmo/sncosmo.github.io#4

**Comment by kbarbary** [comment] 2016-11-16 15:42
Is there any real use for salt2 v1.0 these days? I think we should maybe just remove it.

**Comment by rbiswas4** [comment] 2016-11-16 19:34
I have never used SNCosmo with that version. So, agreed.

**Comment by AlexGKim** [comment] 2016-11-16 20:03
I don’t use it myself.

Alex

**Comment by kbarbary** [comment] 2016-11-16 23:13
I took a look at the snfit code and it is no longer supported there either. Will remove.

**Comment by kbarbary** [comment] 2016-11-17 04:47
Removed in 575ce7f.

**Closed by kbarbary** 2016-11-17 04:47 UTC
